config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord

  validates :name, :address, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_navbar.html.erb
<div class="navbar navbar-mine">
<%= link_to "Simple Airbnb", flats_path %>
<%= link_to "Add Flat", new_flat_path %>
</div>

app/views/flats/edit.html.erb
<%= render "flats/navbar" %>

<div class="container-form">
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
</div>

app/views/flats/index.html.erb
<%= render "flats/navbar" %>

<div class="container">
  <h1>All our Flats</h1>
  <p>Our <%= Flat.count %> flats!</p>

  <div class="grid">
    <% @flats.each do |flat| %>
      <div class="card-trip">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />

        <div class="card-trip-infos">
          <h2><%= flat.name %></h2>
          <p><%= flat.description %></p>
          <p><em><%= flat.address %></em></p>
        </div>

        <div class="card-trip-icons">
          <div class="card-trip-people">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" /></svg>
            <p><%= flat.number_of_guests %></p>
          </div>
          <div class="card-trip-price">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.25 7.756a4.5 4.5 0 100 8.488M7.5 10.5h5.25m-5.25 3h5.25M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            <p><%= flat.price_per_night %></p>
          </div>
        </div>


          <div class="flats-crud">
            <div><%= link_to "About this flat", flat_path(flat) %> </div>
            <div><%= button_to "", edit_flat_path(flat), :class => 'fa-solid fa-pen-to-square btn', method: :get %></div>
            <div><%= button_to "", flat_path(flat), :class => 'fa-solid fa-trash-can btn', method: :delete %>
          </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render "flats/navbar" %>

<div class="container-form">
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
</div>

app/views/flats/show.html.erb
<%= render "flats/navbar" %>
<div class="banner" style="background-image: url('https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg')">

<div class="container">
<div class="grid-2col">
<div class="flat-information">

<div class="flat-information-headers">
<h2><%= @flat.name %></h2>
<p><%= @flat.address %></p>
</div>

<div class="flat-information-content">
<h3>A bit more about this flat...</h3>
<p><%= @flat.description %>.</p>
<div class="map" style="background-image: url('https://images.squarespace-cdn.com/content/v1/54f31d5fe4b04ab92e183f79/1523905505470-555WPMY7ML5KQ5IZAC7Z/Brackenbury+cropped+Jpeg.jpg')"></div>
</div>
 </div>

<div class="flat-form">

<div class="flat-form-book">
  <form action="">
  <div class="input-group">
            <span class="input-group-text" id="start-date-label">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="start-date" aria-describedby="start-date-label">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-text" id="end-date-label">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="end-date" aria-describedby="start-date-label">
          </div>
          <input type="submit" value="Book" class="btn btn-primary mt-2" style="width: 100%">
        </form></div>

    <div class="flat-form-details">
      <h3>Details</h3>
      <div class="flat-form-details-flex">
      <p><%= @flat.number_of_guests %> people</p>
      <p><%= @flat.price_per_night %>€</p>
      </div>
    </div>

    <div class="flat-show-card">
          <h6 class="no-mb">Share</h6>
          <div class="flex">
            <i class="fa-brands fa-facebook-square me-2"></i>
            <i class="fa-brands fa-twitter-square me-2"></i>
            <i class="fa-brands fa-pinterest-square me-2"></i>
          </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>